@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

AddRelTag("sync", $textColor="black", $lineColor="black", $lineStyle = DashedLine())

LAYOUT_WITH_LEGEND()

title Order Management Architecture

System_Ext(api, "api", "Places orders")
System(apiGateway, "API Gateway", "Receives external API calls")
System(iam, "IAM", "Stores Identities, does Authentication/ Authorization on API calls")
System(bff, "Backend For Frontend Service", "Proxies calls to domain services")
System(orderSvc, "OrderService", "Manages order data. Stores it in program memory")

Rel_D(api, apiGateway, "Places orders", $tags="sync")
Rel_L(iam, apiGateway, "Authenticates/Authorizes clients", $tags="sync")
Rel_D(apiGateway,bff, "Message bus message to BFF", $tags="sync")
Rel_D(bff,orderSvc, "Sends order details", $tags="sync")

@enduml